datasets:
  iconqa:
    # data_dir: ${env.data_dir}/datasets
    data_type: images # [images|videos|features]

    build_info:
      # Be careful not to append minus sign (-) before split to avoid itemizing
      annotations:
        train:
          storage: iconqa/annotations/train.json
        val:
          storage: iconqa/annotations/val.json
        test:
          storage: iconqa/annotations/test.json
      images:
        train:
          storage: iconqa/iconqa/train/choose_txt
        val:
          storage: iconqa/iconqa/val/choose_txt
        test:
          storage: iconqa/iconqa/test/choose_txt